name: Publish to pub.dev

on:
  pull_request:
    branches: [ release-workflow ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'publish pusher-channels-flutter package'
        id: publish
        uses: k-paxian/dart-package-publisher@master
        with:
          format: true
          flutter: true
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
      - name: 'Commit release tag'
        if: steps.publish.outputs.success
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{steps.publish.outputs.package}}-${{steps.publish.outputs.localVersion}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
      